DELETE http://localhost:8080/api/users/61391eba2e43ab34e71f0deb
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTM5MTlmZTM3ZWFjODYxZTUwZmNhNzYiLCJpYXQiOjE2MzExMzI1MjcsImV4cCI6MTYzMTE0NjkyN30.uVVHlsyjuHU16KcQobo77qcuoCr-oNyhGPFNlS4PxAA